### PR TITLE
Improve navbar and allow setting SCSS variables in `config.toml`

### PR DESCRIPTION
**Pull request by salim-b**
This PR

-  allows setting the SCSS variable values via `config.toml` and renames most SCSS variables to have more logical semantic prefixes.

- improves / simplifies navigation bar styling.

- removes `params.logo_width` from `config.toml` (i.e. reverts https://github.com/themefisher/airspace-hugo/commit/563b41cfc4c31edfd5908f50e2a625b7c39eca89) since this "static" approach to define the logo width interferes with a constant navbar height (which is desirable to allow for responsive page height); one can still downscale the logo image file or add some custom CSS to control the logo size.

- outsources the style for responsive page height into a separate class to be more easily reusable.

- makes some cosmetic changes and adds some additional comments in the modified files.

- updates the precompiled SCSS files under `exampleSite/resources/_gen/` (relevant for users  [without the extended version of Hugo](https://discourse.gohugo.io/t/should-i-use-hugo-extended-for-a-new-hugo-project/13954/6))

Since these changes are interdependent, I dared to put them in a single PR. Hope that's fine.

### CODE REVIEW

**Comment by somratpro** [comment]
Hey @salim-b 

Thanks for your lot of contribution, we have merged all your PR, but we can't accept this PR right now, We have a plan to update this template in our own way. and this PR will conflict with it. we will update this theme in our new structure very soon. stay tuned.

**Comment by salim-b** [comment]
Hi @somratpro 

Ok, I'm curious about that. May I ask some questions?

1. Are you developping this in private or can I have a look at this work in progress? I wonder what parts of the theme you're actually changing because I'd like to submit some more PRs but at the same time would really like to avoid unnecessary work (i.e. PRs that simply end up closed like this one because of conflicts with your planned changes).
 
2. Are you by any chance also planning to migrate the theme to Bootstrap 4 and [Bootstrap Icons](https://icons.getbootstrap.com/) (instead of Ionicons)?

3. Do you have some time estimate about when you will release this update?

**Comment by somratpro** [comment]
Hey,

We already have updated a theme like this, check it out https://github.com/gethugothemes/apollo-hugo/

We will update our all theme step by step, can't ensure the time limit.

**Comment by salim-b** [comment]
Thanks for the link. I see the _Apollo_ theme is based on Bootstrap 4 and the navigation bar seems cleaner, nice. Looking forward to the update!

**Pull request closed without merging**
